[package]
name = "lib-ray-tracer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24.7"
nalgebra = "0.32.3"
progress_bar = "1.0.5"
rand = "0.8.5"
real_interval = "0.1.0"
