[package]
name = "ray-tracer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24.7"
lib-ray-tracer = { path = "../" }
nalgebra = "0.32.3"
rand = "0.8.5"
speedy2d = "1.12.0"
